version: '2'
services:
  web:
    build: .
    volumes:
       - /etc/localtime:/etc/localtime:ro
    environment:
      URL: 'http://beta.parliament.uk'
      SAUCE_USERNAME: 'unknown'
      SAUCE_ACCESS_KEY: 'unknown'
    command: make isauce